### ISSUE TITLE
Robot will not move

### ISSUE THREAD

**Issue by jsfurtad** [lagadic/demo_pioneer#3] opened 2016-06-01 19:27 UTC
Hi,

This is the first time I'm using V-Rep. I previously used Gazebo on ROS. I am trying out the "Pioneer 3D-X controlled via a visual servoing law" tutorial found at http://wiki.ros.org/vrep_ros_bridge/Tutorials/Pioneer%203D-X%20controlling%20its%20pose%20via%20a%20visual%20servoing%20law . The robot will however not move.

I am currently using ROS Indigo, Ubuntu 14.04.4 LTS (Trusty Tahr), and V-REP_PRO_EDU_V3_3_1_64_Linux.

I have attached screenshots of everything I have up and running during the simulation.
https://drive.google.com/open?id=0ByBul3e5THseVzdUa2k5aHVkMkU

Thanks in advance!
Joshua

**Comment by jokla** [comment] 2016-06-02 06:46
Hi Joshua, 

I will try to reproduce the error in my pc and I will let you know. 

Giovanni

**Comment by jsfurtad** [comment] 2016-06-03 18:20
Hi Giovanni,

Sure no problem.

Joshua

**Comment by jokla** [comment] 2016-06-04 13:22
Hi Joshua,
With the new version of V-REP_PRO_EDU_V3_3_1_64_Linux we need an additional step. We need to create a link pointing to the file libv_repExtRos.so in the v-rep root folder.

Here the instructions:
- Go (via terminal) to the folder /V-REP_PRO_EDU_V3_3_1_64_Linux
- Create a link to libv_repExtRos.so:
`$    ln -s compiledRosPlugins/libv_repExtRos.so ` 
- Check if the link was created correctly:
    `$  ls -ll` 

    ...
   `libv_repExtRos.so -> compiledRosPlugins/libv_repExtRos.so`
    ...

- go to vrep_ros_bridge folder `$ roscd vrep_ros_bridge`
- checkout the branch `master` (compatible with indigo)
- `git pull ` to update vrep_ros_bridge 
- `$ catkin_make` in catkin_ws
- launch roscore: `$ roscore`
- launch v-rep
- launch the demo:
`$ roslaunch demo_pioneer demo-visual-servo-pioneer-simulation.launch`

You will see an error like:
`Lua runtime error: [string "MAIN SCRIPT"]:15: Object is not a joint. (simOpenModule)`
but the demo will work. (I will check that problem)

Let me know if it is working for you!

Giovanni

**Comment by jsfurtad** [comment] 2016-06-06 21:29
Hey Giovanni!

Thanks a lot. It worked for me. Have you ever happened to use the RosPlugin provided by Copellia (http://www.coppeliarobotics.com/helpFiles/en/rosInterfaceOverview.htm) ? If so, how would you compare the ros bridge and the ros plugin? Once again, thanks for the help.

Sincerely,
Joshua

**Comment by jsfurtad** [comment] 2016-07-04 23:30
Hi Giovanni!

I realized the V-REP ROS bridge only provides handlers for IMU and vision sensors. I am looking into creating handlers for LIDAR and GPS sensors. Could you advise me on how to go about doing the same. I really appreciate all the help you have provided and thanks for taking the time and effort to create the V-REP ROS bridge.

Sincerely,
Joshua

**Comment by jokla** [comment] 2016-07-05 08:33
Hi Joshua,

Yes, you are right, there is no handler for LIDAR and GPS.
Which LIDAR sensor you want to use in V-REP? Velodyne VPL-16?

I think it would be a good idea to take a look at the new [V-REP ROS interface](http://www.coppeliarobotics.com/helpFiles/index.html). Probably it will be easy to publish info from the LIDAR and the GPS. I suggest you to try it.

If the previous plugin is not what you need, but just in this case, you could add the handlers to our plugin. You can copy paste another plugin folder and change names and functions, mainly the function `handleSimulation()` and `_initialize()` (see for example [this commit](https://github.com/lagadic/vrep_ros_bridge/pull/33/commits/86d3b0c12feeec7be11319862e6d5c1ac420a189), that added a new handler). 

Giovanni

**Comment by jsfurtad** [comment] 2016-07-05 21:11
Hi Giovanni,

I am using the 2D LIDAR in V-REP. I was considering using the V-REP ROS Interface. I'll definitely have a look into that. Thanks for the guidance on how create a new handler. Is there any particular advantage of the V-REP ROS bridge (based on ROS Plugin) over the ROS Interface? I prefer to use just one interface for my project. 

Thanks,
Joshua

**Comment by jokla** [comment] 2016-07-06 12:26
Maybe @ricsp  can help me to answer this question :p

So, we started the project because the old ROS plugin was not very flexible and customizable, and we needed for example:
- to get images from the camera at a different frame rate than the simulation time (that is higher).  
- to decide if to use a color or a black and white image.
- to subscribe to custom messages, do some processing in c++ and apply the command to the robot.

In general, the plugin should be one of the fastest way to manage a simulation in V-REP from an external controller.

I would suggest to try the official plugin and only if you see that you are missing something, try ours. I have never tried the last ROS interface of V-REP so I am not able to tell you more about this.

Giovanni

**Comment by fspindle** [comment] 2016-08-16 12:46
I close this issue since the end of the discussion is out of scope.

**Closed by fspindle** 2016-08-16 12:46 UTC
